"""
This type stub file was generated by pyright.
"""

import time
from typing import Optional
from .api_jwk import PyJWKSet, PyJWTSetWithTimestamp

class JWKSetCache:
    def __init__(self, lifespan: int) -> None:
        ...
    
    def put(self, jwk_set: PyJWKSet) -> None:
        ...
    
    def get(self) -> Optional[PyJWKSet]:
        ...
    
    def is_expired(self) -> bool:
        ...
    


