version: '3.3'

services:

  ext-api:
    build: .
    command: tail -F /none
    container_name: ext-api
    ports:
      - 8080:8080
    volumes:
      - .:/var/app
      - ~/.bash_history:/root/.bash_history
