version: '3.4'

services:

  ext-ui:
    image: ulauncher/ext-ui:dev
    container_name: ext-ui
    environment:
      - REACT_APP_AUTH0_DOMAIN=$AUTH0_DOMAIN
      - REACT_APP_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
      - REACT_APP_API_BASE_URL=http://localhost:8080
    ports:
      - 3001:80

  ext-api:
    build: .
    command: tail -F /none
    entrypoint: ""
    container_name: ext-api
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    volumes:
      - .:/var/app
      - ~/.bash_history:/root/.bash_history

  # don't run anything in this container
  ext-api-sync-versions:
    build: .
    container_name: ext-api-sync-versions
    command: "true"
    entrypoint: ""
    restart: "no"

  # don't run anything in this container
  ext-api-sync-github-stars:
    build: .
    container_name: ext-api-sync-github-stars
    command: "true"
    entrypoint: ""
    restart: "no"

  mongodb:
    image: mongo:4.0.9
    container_name: ext-mongodb
    restart: always
    volumes:
      - ./.db/mongo/db:/data/db
      - ./.db/mongo/configdb:/data/configdb
