version: '3.4'

services:

  # ext-ui:
  #   image: ulauncher/ext-ui:dev
  #   container_name: ext-ui
  #   environment:
  #     - REACT_APP_AUTH0_DOMAIN=$AUTH0_DOMAIN
  #     - REACT_APP_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
  #     - REACT_APP_API_BASE_URL=http://localhost:8080
  #   ports:
  #     - 3001:80

  ext-api:
    build: .
    command: tail -F /none
    entrypoint: ""
    container_name: ext-api
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    volumes:
      - .:/var/app
      - ~/.bash_history:/root/.bash_history
    environment:
      - AUTH0_DOMAIN
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
      - GITHUB_API_USER
      - GITHUB_API_TOKEN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - EXTENSIONS_TABLE_NAME
      - EXT_IMAGES_BUCKET_NAME
      - MONGODB_CONNECTION
      - DB_NAME
      - VIRTUAL_HOST=$DOMAIN_NAME
      - LETSENCRYPT_HOST=$DOMAIN_NAME
      - LETSENCRYPT_EMAIL
      - LOG_LEVEL

  mongodb:
    image: mongo:5
    container_name: ext-mongodb
    restart: always
    volumes:
      - ./.db/mongo/db:/data/db
      - ./.db/mongo/configdb:/data/configdb
