version: '3.3'

services:

  ext-api:
    build: .
    command: tail -F /none
    container_name: ext-api
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    volumes:
      - .:/var/app
      - ~/.bash_history:/root/.bash_history

  mongodb:
    image: mongo:3.4.10
    restart: always
    ports:
      - 27017:27017
