services:

  # ext-ui:
  #   image: ulauncher/ext-ui:dev
  #   container_name: ext-ui
  #   environment:
  #     - REACT_APP_AUTH0_DOMAIN=$AUTH0_DOMAIN
  #     - REACT_APP_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
  #     - REACT_APP_API_BASE_URL=http://localhost:8080
  #   ports:
  #     - 3001:80

  mongodb:
    image: mongo:8
    container_name: ext-mongodb
    restart: always
    volumes:
      - ./.db/mongo/db:/data/db
      - ./.db/mongo/configdb:/data/configdb
