#!/bin/bash

set -e
export AUTH0_DOMAIN=ulauncher.auth0.com
export AUTH0_CLIENT_ID=AUTH0_CLIENT_ID
export AUTH0_CLIENT_SECRET=AUTH0_CLIENT_SECRET
export EXTENSIONS_TABLE_NAME=EXTENSIONS_TABLE_NAME
export EXT_IMAGES_BUCKET_NAME=EXT_IMAGES_BUCKET_NAME
export PYTHONPATH=`pwd`
export MONGODB_CONNECTION=mongodb://mongodb:27017/
export DB_NAME=ext_api_dev

main () {
    test-pylint db_migrations ext_api tests
    test-flake8 db_migrations ext_api tests
    test-pytest db_migrations ext_api tests
}

test-pylint () {
    echo
    echo '[ test: pylint ]'
    pylint --output-format=colorized $@
}

test-flake8 () {
    echo
    echo '[ test: flake8 ]'
    flake8 $@
}

test-pytest () {
    echo
    echo '[ test: pytest ]'
    py.test $@ tests
}

main
