"""
This type stub file was generated by pyright.
"""

import os
import os.path
import re
import sys
import time
import threading
import inotify.constants
from inotify.adapters import Inotify

COMPILED_EXT_RE = ...
class Reloader(threading.Thread):
    def __init__(self, extra_files=..., interval=..., callback=...) -> None:
        ...
    
    def add_extra_file(self, filename): # -> None:
        ...
    
    def get_files(self): # -> list[Any]:
        ...
    
    def run(self):
        ...
    


has_inotify = ...
if sys.platform.startswith('linux'):
    has_inotify = ...
if has_inotify:
    class InotifyReloader(threading.Thread):
        event_mask = ...
        def __init__(self, extra_files=..., callback=...) -> None:
            ...
        
        def add_extra_file(self, filename): # -> None:
            ...
        
        def get_dirs(self): # -> set[Any]:
            ...
        
        def run(self): # -> None:
            ...
        
    
    
else:
    class InotifyReloader:
        def __init__(self, extra_files=..., callback=...) -> None:
            ...
        
    
    
preferred_reloader = ...
reloader_engines = ...
