"""
This type stub file was generated by pyright.
"""

from cryptography.hazmat._oid import AttributeOID, AuthorityInformationAccessOID, CRLEntryExtensionOID, CertificatePoliciesOID, ExtendedKeyUsageOID, ExtensionOID, NameOID, OCSPExtensionOID, ObjectIdentifier, OtherNameFormOID, PublicKeyAlgorithmOID, SignatureAlgorithmOID, SubjectInformationAccessOID

__all__ = ["AttributeOID", "AuthorityInformationAccessOID", "CRLEntryExtensionOID", "CertificatePoliciesOID", "ExtendedKeyUsageOID", "ExtensionOID", "NameOID", "OCSPExtensionOID", "ObjectIdentifier", "OtherNameFormOID", "PublicKeyAlgorithmOID", "SignatureAlgorithmOID", "SubjectInformationAccessOID"]
