"""
This type stub file was generated by pyright.
"""

import importlib.util
import importlib.machinery
import os
import sys
import traceback
from gunicorn import debug, util
from gunicorn.arbiter import Arbiter
from gunicorn.config import Config, get_default_config_file

class BaseApplication:
    """
    An application interface for configuring and loading
    the various necessities for any given web framework.
    """
    def __init__(self, usage=..., prog=...) -> None:
        ...
    
    def do_load_config(self): # -> None:
        """
        Loads the configuration
        """
        ...
    
    def load_default_config(self): # -> None:
        ...
    
    def init(self, parser, opts, args):
        ...
    
    def load(self):
        ...
    
    def load_config(self):
        """
        This method is used to load the configuration from one or several input(s).
        Custom Command line, configuration file.
        You have to override this method in your class.
        """
        ...
    
    def reload(self): # -> None:
        ...
    
    def wsgi(self):
        ...
    
    def run(self):
        ...
    


class Application(BaseApplication):
    def chdir(self): # -> None:
        ...
    
    def get_config_from_filename(self, filename): # -> dict[str, Any]:
        ...
    
    def get_config_from_module_name(self, module_name): # -> dict[str, Any]:
        ...
    
    def load_config_from_module_name_or_filename(self, location): # -> dict[str, Any]:
        """
        Loads the configuration file: the file is a python file, otherwise raise an RuntimeError
        Exception or stop the process if the configuration file contains a syntax error.
        """
        ...
    
    def load_config_from_file(self, filename): # -> dict[str, Any]:
        ...
    
    def load_config(self): # -> None:
        ...
    
    def run(self):
        ...
    


