"""
This type stub file was generated by pyright.
"""

import typing
from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions, openssl as rust_openssl

if typing.TYPE_CHECKING:
    ...
_Reasons = rust_exceptions._Reasons
class UnsupportedAlgorithm(Exception):
    def __init__(self, message: str, reason: _Reasons | None = ...) -> None:
        ...
    


class AlreadyFinalized(Exception):
    ...


class AlreadyUpdated(Exception):
    ...


class NotYetFinalized(Exception):
    ...


class InvalidTag(Exception):
    ...


class InvalidSignature(Exception):
    ...


class InternalError(Exception):
    def __init__(self, msg: str, err_code: list[rust_openssl.OpenSSLError]) -> None:
        ...
    


class InvalidKey(Exception):
    ...


