"""
This type stub file was generated by pyright.
"""

import select
import socket
from functools import partial

__all__ = ["wait_for_read", "wait_for_write"]
def select_wait_for_socket(sock: socket.socket, read: bool = ..., write: bool = ..., timeout: float | None = ...) -> bool:
    ...

def poll_wait_for_socket(sock: socket.socket, read: bool = ..., write: bool = ..., timeout: float | None = ...) -> bool:
    ...

def wait_for_socket(sock: socket.socket, read: bool = ..., write: bool = ..., timeout: float | None = ...) -> bool:
    ...

def wait_for_read(sock: socket.socket, timeout: float | None = ...) -> bool:
    """Waits for reading to be available on a given socket.
    Returns True if the socket is readable, or False if the timeout expired.
    """
    ...

def wait_for_write(sock: socket.socket, timeout: float | None = ...) -> bool:
    """Waits for writing to be available on a given socket.
    Returns True if the socket is readable, or False if the timeout expired.
    """
    ...

